const SUPABASE_URL="https://dzlkpulknbpxibcvdhom.supabase.co";
const SUPABASE_KEY="sb_publishable_v4v_GxlTHZNqSYqO-Ij7bQ_IPPFU7sk";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const ADMIN_EMAIL="pecristoastacio@gmail.com";
const seedEvents=[
{id:1,provider:'Netflix',sport:'NFL',title:'Packers @ Rams',date:'2026-11-25',time:'21:00',region:'DO',rights:'Global / verify account',verified:true,status:'UPCOMING'},
{id:2,provider:'Netflix',sport:'NFL',title:'Packers @ Bears',date:'2026-12-25',time:'14:00',region:'DO',rights:'Global / verify account',verified:true,status:'UPCOMING'},
{id:3,provider:'Disney+',sport:'Football',title:'ESPN Live Football',date:'2026-10-06',time:'20:00',region:'DO',rights:'Disney+ Premium RD / event rights vary',verified:true,status:'LIVE'},
{id:4,provider:'DAZN',sport:'Boxing',title:'DAZN Fight Night',date:'2026-10-10',time:'21:00',region:'DO',rights:'Available subject to blackout',verified:true,status:'UPCOMING'},
{id:5,provider:'Paramount+',sport:'Football',title:'UEFA / Soccer Sports Hub',date:'2026-10-07',time:'15:00',region:'DO',rights:'Validate rights for Dominican Republic',verified:false,status:'UPCOMING'},
{id:6,provider:'DISH',sport:'Basketball',title:'NBA Basketball',date:'2026-10-06',time:'20:00',region:'US',rights:'DISH subscription',verified:false,status:'LIVE',channel:'140',sat:'119°W'}];
const channels=[{ch:'140',name:'ESPN',sat:'119°W',tp:'TP 12',type:'HD'},{ch:'150',name:'FS1',sat:'110°W',tp:'TP 18',type:'HD'},{ch:'200',name:'CNN',sat:'119°W',tp:'TP 09',type:'HD'},{ch:'136',name:'FX',sat:'110°W',tp:'TP 21',type:'HD'}];
const users=[{name:'Administrator',email:'admin@codexastacio.app',role:'Admin',status:'Active',services:['DISH','Disney+','Paramount+','DAZN','Netflix']},{name:'Demo User',email:'demo@codexastacio.app',role:'User',status:'Active',services:['DISH']}];
let state={logged:false,role:'User',email:'',view:'guide',provider:'all',sport:'all',events:[...seedEvents]};const app=document.querySelector('#app');
function login(){app.innerHTML='<main class="wrap"><section class="panel login"><div class="brand">CodeXaStacio TV Guide</div><p class="muted">Acceso seguro con Supabase</p><form id="login"><input class="input" id="email" placeholder="Usuario o correo" required><br><br><input class="input" id="pw" type="password" placeholder="Contraseña" required><br><br><button class="btn primary" style="width:100%">Entrar</button></form><p class="small muted">Administrador: puede usar pecastacio o su correo.</p><div id="err" class="danger small"></div></section></main>';document.querySelector("#login").onsubmit=async e=>{e.preventDefault();let em=document.querySelector("#email").value.trim();if(em.toLowerCase()==="pecastacio")em=ADMIN_EMAIL;const p=document.querySelector("#pw").value;const {error}=await sb.auth.signInWithPassword({email:em,password:p});if(error)document.querySelector("#err").textContent=error.message;}}
function shell(content){return `<main class="wrap"><header class="top"><div><div class="brand">CodeXaStacio • Universal Sports Finder</div><div class="small muted">Independent TV/streaming guide • Region 🇩🇴 DO • UTC−4</div></div><div><span class="badge">${state.role}</span> <button id="out" class="btn">Salir</button></div></header><nav class="nav"><button data-v="guide" class="btn ${state.view==='guide'?'active':''}">${state.role==='Admin'?'Guía':'Buscador'}</button>${state.role==='Admin'?`<button data-v="channels" class="btn ${state.view==='channels'?'active':''}">110°/119°</button><button data-v="admin" class="btn ${state.view==='admin'?'active':''}">Admin</button><button data-v="users" class="btn ${state.view==='users'?'active':''}">Usuarios</button>`:''}</nav>${content}<footer class="footer">Prototype • Los derechos deportivos cambian por territorio. La versión productiva debe validar fuentes y disponibilidad antes de publicar.</footer></main>`}
function guide(){let current=users.find(u=>u.email===state.email)||users[1];let allowed=state.role==='Admin'?['DISH','Disney+','Paramount+','DAZN','Netflix']:current.services;let providers=['all',...allowed],sports=['all','NFL','Football','Basketball','Boxing'];let list=state.events.filter(x=>allowed.includes(x.provider)&&(state.provider==='all'||x.provider===state.provider)&&(state.sport==='all'||x.sport===state.sport));return shell(`<section class="panel"><div class="top"><div><h2 style="margin:0">Eventos & transmisiones</h2><span class="muted small">${list.length} resultados • TV + streaming</span></div><input id="search" class="input" style="max-width:390px" placeholder="Buscar equipo, liga, deporte, plataforma…"></div><div class="chips">${providers.map(p=>`<button data-p="${p}" class="chip ${state.provider===p?'active':''}">${p==='all'?'Todos':p}</button>`).join('')}</div><div class="chips">${sports.map(s=>`<button data-s="${s}" class="chip ${state.sport===s?'active':''}">${s==='all'?'Todos los deportes':s}</button>`).join('')}</div><div id="cards" class="grid">${cards(list)}</div></section>`)}
function cards(list){return list.map(e=>`<article class="card event" data-search="${(e.provider+' '+e.sport+' '+e.title).toLowerCase()}"><div class="row"><strong>${e.provider}</strong><span class="badge ${e.status==='LIVE'?'ok':''}">${e.status}</span></div><div class="small muted">${e.sport}</div><h3>${e.title}</h3><div>📅 ${e.date} • 🕐 ${e.time} RD</div>${e.sat?`<div class="small">📡 ${e.channel} • ${e.sat}</div>`:''}<div class="notice small"><strong>${e.verified?'✓ Verificado':'⚠ Validar'}:</strong> ${e.rights}</div></article>`).join('')||'<p class="muted">Sin resultados.</p>'}
function channelView(){return shell(`<section class="panel"><h2>Canales satelitales 110°W / 119°W</h2><div class="tablewrap"><table><thead><tr><th>Canal</th><th>Network</th><th>Satélite</th><th>Transponder</th><th>Formato</th></tr></thead><tbody>${channels.map(c=>`<tr><td>${c.ch}</td><td>${c.name}</td><td>${c.sat}</td><td>${c.tp}</td><td>${c.type}</td></tr>`).join('')}</tbody></table></div><p class="small warn">Datos técnicos de esta demo son ilustrativos hasta conectar/importar la fuente satelital validada.</p></section>`)}
function admin(){return shell(`<div class="stats"><div class="panel stat"><b>${state.events.length}</b><div class="small muted">Eventos</div></div><div class="panel stat"><b>${channels.length}</b><div class="small muted">Canales</div></div><div class="panel stat"><b>${users.length}</b><div class="small muted">Usuarios</div></div><div class="panel stat"><b>DO</b><div class="small muted">Región</div></div></div><section class="panel"><h2>Agregar evento</h2><form id="eventForm" class="formgrid"><input id="title" class="input" placeholder="Evento" required><select id="prov" class="input"><option>Disney+</option><option>Paramount+</option><option>DAZN</option><option>Netflix</option><option>DISH</option></select><input id="sport" class="input" placeholder="Deporte" required><input id="date" class="input" type="date" required><input id="time" class="input" type="time" required><input id="rights" class="input" placeholder="Derechos / disponibilidad" required><button class="btn primary">Guardar evento</button></form></section><section class="panel" style="margin-top:12px"><h2>Regional Rights Engine</h2><p class="muted">Modelo preparado para provider + event + country + rights_scope + start_time + verified + blackout.</p><div class="notice">✓ Fuente verificada &nbsp; ⚠ Validación pendiente &nbsp; 🚫 Blackout regional &nbsp; 📡 Satellite EPG</div></section>`)}
function userView(){let streams=['DAZN','Disney+','Paramount+','Netflix'];return shell(`<section class="panel"><h2>Control de usuarios y servicios</h2><p class="muted">DISH 110°W/119°W está incluido por defecto. Activa o restringe plataformas de streaming individualmente.</p><div class="tablewrap"><table><thead><tr><th>Usuario</th><th>Estado</th><th>DISH 110/119</th><th>Streaming autorizado</th></tr></thead><tbody>${users.filter(u=>u.role==='User').map((u,i)=>`<tr><td><strong>${u.name}</strong><br><span class="small muted">${u.email}</span></td><td>${u.status}</td><td><span class="badge ok">✓ Siempre activo</span></td><td>${streams.map(s=>`<label class="badge" style="display:inline-block;margin:3px"><input type="checkbox" data-service="${s}" data-user="${i}" ${u.services.includes(s)?'checked':''}> ${s}</label>`).join('')}</td></tr>`).join('')}</tbody></table></div><div class="notice small">Demo: los cambios funcionan durante la sesión. La siguiente fase conectará usuarios y permisos a una base de datos para que persistan de forma segura.</div></section>`)}
function render(){if(!state.logged)return login();app.innerHTML=state.view==='channels'?channelView():state.view==='admin'?admin():state.view==='users'?userView():guide();document.querySelector('#out').onclick=()=>sb.auth.signOut();document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;render()});document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.provider=b.dataset.p;render()});document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{state.sport=b.dataset.s;render()});let search=document.querySelector('#search');if(search)search.oninput=()=>document.querySelectorAll('.event').forEach(c=>c.classList.toggle('hidden',!c.dataset.search.includes(search.value.toLowerCase())));document.querySelectorAll('[data-service]').forEach(x=>x.onchange=()=>{let u=users.filter(u=>u.role==='User')[+x.dataset.user];if(x.checked&&!u.services.includes(x.dataset.service))u.services.push(x.dataset.service);if(!x.checked)u.services=u.services.filter(s=>s!==x.dataset.service)});let f=document.querySelector('#eventForm');if(f)f.onsubmit=e=>{e.preventDefault();state.events.unshift({id:Date.now(),provider:prov.value,sport:sport.value,title:title.value,date:date.value,time:time.value,region:'DO',rights:rights.value,verified:false,status:'UPCOMING'});state.view='guide';render()}}
async function initAuth(){const {data:{session}}=await sb.auth.getSession();if(session){state.logged=true;state.email=session.user.email;const {data:p}=await sb.from('profiles').select('role,status').eq('id',session.user.id).single();state.role=p?.role==='admin'?'Admin':'User';render()}else login();sb.auth.onAuthStateChange(async(_e,s)=>{if(s){state.logged=true;state.email=s.user.email;const {data:p}=await sb.from('profiles').select('role,status').eq('id',s.user.id).single();state.role=p?.role==='admin'?'Admin':'User';render()}else{state.logged=false;login()}})}
initAuth();